- name: install apache
  dnf:
          name: httpd
          state: installed
 
- name: start service
  service:
          name: httpd
          state: started

- name: change index page
  copy:
          src: index.html
          dest: /usr/share/httpd/noindex/index.html
          mode: 0755
