---
- hosts: localhost
  tasks:
  - import_role:
            name: basetemplate
    vars: 
      project: jwhetsel
      vms:
              - name: server-small
                template_name: centos8-server-small
                cloud_password: r3dh4t1!
                #- name: server-medium
                #template_name: centos-server-medium
                #cloud_password: r3dh4t1!
                #- name: server-large
                #template_name: centos-server-large
                #cloud_password: r3dh4t1!
