---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: create namespace for VMS
    become: False
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      definition:
        kind: Project
        apiVersion: project.openshift.io/v1
        metadata:
          name: "user1"
          labels:
            kubernetes.io/metadata.name: "user1"

  - include_role:
      name: zer0glitch.ocpv.create_vm
    vars: 
      project: user1
      vm_name: fedora-custom
      boot_source: fedora
      boot_source_type: pvc
      root_volume_size: 30
      cores: 1
      sockets: 1
      threads: 1
      memory: 2
      password: r3dh4t1!
      data_volumes: 
      - name: drive1
        size: 10Gi
      - name: drive2
        size: 20Gi
      cloud_init: |
              #cloud-config
              user: "jamie"
              password: "r3dh4t1!"
              chpasswd: { expire: False }
