---
- hosts: localhost
  gather_facts: false
  tasks:
          #  - set_fact:
          #cloud_init_secret: 

  - name: create namespace for VMS
    become: False
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      definition:
        kind: Project
        apiVersion: project.openshift.io/v1
        metadata:
          name: "user1"
          labels:
            kubernetes.io/metadata.name: "user1"

  - include_role:
      name: zer0glitch.ocpv.create_vm
    vars: 
      project: user1
      vm_name: fedora-custom
      boot_source: fedora
      boot_source_type: pvc
      root_volume_size: 30
      cores: 1
      sockets: 1
      threads: 1
      memory: 2
      password: r3dh4t1!
      #network_interfaces:
      #- name: eth1
      #  bridge_name: vrb0
      #  vlan_id: 222
      #- name: eth2
      #  bridge_name: vrb0
      #  vlan_id: 222
      data_volumes: 
      - name: drive1
        size: 30Gi
      - name: drive2
        size: 30Gi
      cloud_init: |
              #cloud-config
              user: "jamie"
              password: "r3dh4t1!"
              chpasswd: { expire: False }


  - include_role:
      name: zer0glitch.ocpv.create_vm
    vars: 
      project: user1
      vm_name: fedora-custom2
      boot_source: fedora
      boot_source_type: pvc
      root_volume_size: 30
      cores: 1
      sockets: 1
      threads: 1
      memory: 2
      #      network_interfaces:
      #- name: eth1
      #  bridge_name: vrb0
      #  vlan_id: 222
      #- name: eth2
      #  bridge_name: vrb0
      #  vlan_id: 222
      data_volumes: 
      - name: drive1
        size: 30Gi
      - name: drive2
        size: 30Gi
      cloud_init_secret: |
        #cloud-config
        user: "jamie"
        password: "r3dh4t1!"
        chpasswd: { expire: False }
        ssh_authorized_keys: {{ lookup('file', '~/.ssh/id_rsa.pub') }}

