---
- hosts: localhost
  tasks:

  - name: create namespace for VMS
    become: False
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      definition:
        kind: Project
        apiVersion: project.openshift.io/v1
        metadata:
          name: "user0"
          labels:
            kubernetes.io/metadata.name: "user0"



  - import_role:
      name: zer0glitch.ocpv.create_vm
    vars: 
      project: user0
      vm_name: fedora-custom
      boot_source: fedora
      boot_source_type: pvc
      root_volume_size: 30
      cores: 1
      sockets: 1
      threads: 1
      memory: 2
      password: r3dh4t1!


                #name: "{{ vm_name }}" 
                #name: "{{ boot_source }}"
                #storage: "{{ root_volume_size|default('30') }}Gi"
                #cores: "{{ cores|default('1') }}"
                #sockets: "{{ sockets|default('1') }}"
                #threads: "{{ threads|default('1') }}"
                #memory: "{{ memory|default('2') }}Gi"
                #user: "{{ user|default('redhatuser') }}"
                #password: "{{ password|default('r3dh4t1!') }}"

