---
- hosts: localhost
  tasks:
  - import_role:
      name: create_vm
    vars: 
      project: user0
      vm_name: fedora-custom
      boot_source: fedora
      boot_source_type: pvc
      root_volume_size: 30
      cores: 1
      sockets: 1
      threads: 1
      memory: 2
      password: r3dh4t1!


                #name: "{{ vm_name }}" 
                #name: "{{ boot_source }}"
                #storage: "{{ root_volume_size|default('30') }}Gi"
                #cores: "{{ cores|default('1') }}"
                #sockets: "{{ sockets|default('1') }}"
                #threads: "{{ threads|default('1') }}"
                #memory: "{{ memory|default('2') }}Gi"
                #user: "{{ user|default('redhatuser') }}"
                #password: "{{ password|default('r3dh4t1!') }}"

