---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
namespace: openshift-virtualization-os-images
metadata:
  name: fedora
spec:
  source:
    registry:
      url: "docker://quay.io/kubevirt/fedora-cloud-container-disk-demo:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
namespace: openshift-virtualization-os-images
metadata:
  name: centos
spec:
  source:
    registry:
      url: "docker://quay.io/kubevirt/centos8-container-disk-images:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
