---
- hosts: localhost
  become: True
  tasks:
 
  - name: install vim
    dnf:
     name: "{{ item }}"
     state: installed
    loop:
    - python3-kubernetes
    - python3-openshift
    - python3-jsonpatch
    - vim

  - name: get virtctl
    get_url:
      url: https://github.com/kubevirt/kubevirt/releases/download/v0.41.0/virtctl-v0.41.0-linux-amd64
      dest: /usr/local/bin/virtctl
      mode: 0755



