- hosts: localhost
  become: True
  vars:
      num_users: 1
      default_pass: 'r3dh4t1!'
      
  tasks:
  - name: Create Users
    user: 
      name: "user{{ item }}"
      password: "{{ default_pass | password_hash('sha512') }}"
      groups: wheel
    with_sequence: start=0 end={{ num_users }} stride=1

  - name: create kube config directory
    file:
      mode: 0700
      path: "/home/user{{ item }}/.kube"
      state: directory
      owner: "user{{ item }}"
      group: "user{{ item }}"
    with_sequence: start=0 end={{ num_users }} stride=1

  - name: copy kubeconfig to tmp
    shell: "sudo cp /home/lab-user/install/auth/kubeconfig  /tmp/kubeconfig && sudo chmod 755 /tmp/kubeconfig"
    #    changed_when: True
    #failed_when: False

  - name: set default user
    set_fact:
       _my_user: "{{ ansible_facts['env']['SUDO_USER']|default('root') }}"

  - name: create kube dir
    file:
      path: "/home/{{ _my_user }}/.kube"
      state: directory
      mode: 0700
      owner: "{{ _my_user }}"

  - name: copy kube config
    become: True
    copy:
      src: "/tmp/kubeconfig"
      dest: "/home/{{ _my_user }}/.kube/config"

  - name: copy kube config
    become: True
    copy:
      src: "/tmp/kubeconfig"
      dest: "/home/user{{ item }}/.kube/config"
      owner: "user{{ item }}"
      group: "user{{ item }}"
    with_sequence: start=0 end={{ num_users }} stride=1

  - name: remove kubconfig
    file:
      path: /tmp/kubeconfig
      state: absent

  - name: Create user projects
    become: False
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      definition:
        kind: Project
        apiVersion: project.openshift.io/v1
        metadata:
          name: "user{{ item }}"
          labels:
            kubernetes.io/metadata.name: "user{{ item }}"
    with_sequence: start=0 end={{ num_users }} stride=1
