- hosts: localhost
  become: True
  vars:
      num_users: 1
      default_pass: 'r3dh4t1!'
      
  tasks:
  - name: Create Users
    user: 
      name: "user{{ item }}"
      password: "{{ default_pass | password_hash('sha512') }}"
      groups: wheel
    with_sequence: start=0 end={{ num_users }} stride=1

# Install virtctl

  - name: get virtctl
    get_url: 
      url: https://github.com/kubevirt/kubevirt/releases/download/v0.41.0/virtctl-v0.41.0-linux-amd64
      dest: /usr/local/bin/virtctl
      mode: 0755

  - name: create kube config directory
    file:
      mode: 0700
      path: "/home/user{{ item }}/.kube"
      state: directory
      owner: "user{{ item }}"
      group: "user{{ item }}"
    with_sequence: start=0 end={{ num_users }} stride=1

  - name: copy kubeconfig to tmp
    shell: sudo cp /home/lab-user/install/auth/kubeconfig /tmp/kubeconfig && sudo chmod 755 /tmp/kubeconfig
    
  - name: set default user
    set_fact:
            my_user: "{{ ansible_facts['env']['SUDO_USER']  }}"

  - name: create kube dir
    file:
      path: "/home/{{ my_user }}/.kube"
      state: directory
      mode: 0700
      owner: "{{ my_user }}"

  - name: copy kube config
    become: True
    copy:
      src: "/tmp/kubeconfig"
      dest: "/home/{{ my_user }}/.kube/config"

  - name: copy kube config
    become: True
    copy:
      src: "/tmp/kubeconfig"
      dest: "/home/user{{ item }}/.kube/config"
      owner: "user{{ item }}"
      group: "user{{ item }}"
    with_sequence: start=0 end={{ num_users }} stride=1

  - name: remove kubconfig
    file:
      path: /tmp/kubeconfig
      state: absent

  - name: Pause a Deployment.
    become: False
    kubernetes.core.k8s:
    #  kubeconfig: ~/.kube/config
      definition:
        kind: Project
        apiVersion: project.openshift.io/v1
        metadata:
          name: "user{{ item }}"
          labels:
            kubernetes.io/metadata.name: "user{{ item }}"
    with_sequence: start=0 end={{ num_users }} stride=1
