- name: Apply the Openshift Operator Subscriptions
  command:
    cmd: oc apply -f  {{ role_path}}/files/kubevirt-hyperconverged.yaml

- name: Pause for 2 minutes to Allow Openshift Virtualizaion to get installed
  pause:
    minutes: 2

- name: Deploy hyperconverged for Openshift Virtualizaion
  command:
    cmd: "oc apply -f {{ role_path}}/files/hyperconverged.yaml"
  register: deployed_hyperconverged
  retries: 5
  delay: 15
  until: deployed_hyperconverged.rc == 0