- name: Apply the Openshift Operator Subscriptions
  kubernetes.core.k8s:
    template: "{{ role_path }}/files/kubevirt-hyperconverged.yaml"
    #wait: True
    #    wait_condition: 
    #  type: 'Succeeded'
    #  status: True
    #  reason: 'InstallSucceeded'

    #- name: wait for Openshift Virtualizatoin Operator to install
    #kubernetes.core.k8s_info:
    #api_version: v1
    #kind: Operator
    #name: kubevirt-hyperconverged.openshift-cnv
    ##    namespace: 
    #register: result
    ##  until: "'install strategy completed with no errors' in result"
  #retries: 30

  #- debug: var="result"
  
- name: wait for Openshift Virtualizatoin Operator to install
  shell: |
    oc get operators kubevirt-hyperconverged.openshift-cnv  -o yaml
  register: result
  until: "'install strategy completed with no errors' in result.stdout"
  retries: 30


- name: Deploy hyperconverged for Openshift Virtualizaion
  kubernetes.core.k8s:
   template: "{{ role_path }}/files/hyperconverged.yaml"
   #   wait: True
   #wait_condition:
   #  reason: ReconcileCompleted
   #  status: True
   #  type: Available


# TODO: Add a wait for the install
