---
- name: Create virtual machiens
  debug: msg="oc process  -n openshift  {{ item.template_name }} -p CLOUD_USER_PASSWORD={{ item.cloud_password }} -p NAME={{ item.name }}| oc apply -n {{ project }}  -f -"
  loop: "{{ vms }}"

- name: Create virtual machiens
  shell: "oc process  -n openshift  {{ item.template_name }} -p CLOUD_USER_PASSWORD={{ item.cloud_password }} -p NAME={{ item.name }}  | oc apply -n {{ project }}  -f -"
  loop: "{{ vms }}"

- name: start virtual machiens
  shell: "virtctl --namespace={{ project }} start {{ item.name }}"
  loop: "{{ vms }}"
